name: xspectre
description: App for connecting gamers and bringing them together

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^1.1.1
  flutter_signin_button: ^1.1.0
  firebase_core: ^0.5.1
  animated_text_kit: ^2.2.0
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.4
  font_awesome_flutter: ^8.8.1
  chewie: ^0.12.0
  ext_video_player: ^0.0.4
  flutter_web_image_picker: ^0.0.2
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.1
  webscrollbar: ^0.0.2
  page_transition: ^1.1.7+6
  youtube_parser: ^1.1.0
  firebase_auth: ^0.18.2
  shared_preferences: ^0.5.10
  google_sign_in: ^4.5.3
  smooth_scroll_web: ^0.0.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/backgroundImage.jpg
    - images/FireBorder.jpg
    - images/AstroBg.jpg
    - images/HeadPhonesBlog.jpg
    - images/ControllerReviews.jpg
    - images/Fortnite.webp
    - images/Valorant.webp
    - images/Valorant.webp
    - images/JoinUsBackground.webp
    - images/TermsBackground.webp
    - images/TournamentBG.webp
    - images/TournamentSidePic.webp
    - images/CommunityBG.webp
    - images/VideosBackground.webp
    - images/CallOfDuty.webp
    - images/OurVideos.webp
    - images/HomeBG.webp
    - images/OurCreators.webp
    - images/SocialMediaBG.webp
    - images/VideosNewsBG.webp
    - images/ChallengesNewsBG.webp
    - images/OurTeam.webp
    - images/img_not_available.jpeg
    - images/Game1.PNG
    - images/Game2.PNG
    - images/motivationalImage.jpg
    - images/Game3.PNG
    - images/gameImage.jpg
    - images/skeleton.gif
    - images/XspectreLogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:

    - family: Schyler
      fonts:
        - asset: Fonts/BunnyHoney.ttf
    - family: Peaches
      fonts:
        - asset: Fonts/Peaches_Cream.otf
    - family: Heading1
      fonts:
        #         - asset: Fonts/Heading.ttf
        - asset: Fonts/TitilliumWeb-Black.ttf
    - family: Heading2
      fonts:
        - asset: Fonts/WarPriest.ttf
    - family: Heading3
      fonts:
        - asset: Fonts/EvilEmpire.ttf
    - family: Poppins
      fonts:
        - asset: Fonts/Poppins-BlackItalic.ttf
    - family: PoppinsThin
      fonts:
        - asset: Fonts/Poppins-LightItalic.ttf
    - family: Nimble
      fonts:
        - asset: Fonts/Nimble.otf
    - family: Longless
      fonts:
        - asset: Fonts/Longless.ttf
    - family: Impact
      fonts:
        - asset: Fonts/impact.ttf
    - family: Lulo
      fonts:
        - asset: Fonts/LuloClean.ttf
    - family: Jura
      fonts:
        - asset: Fonts/Jura.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

